<?xml version="1.0" encoding="utf-8"?>
<Database Name="TakeoDB" Class="LinqOpticalShopClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=NBC120\sql2008;Failover Partner=192.168.111.252\sql2;Initial Catalog=TakeoDB;Persist Security Info=True;User ID=sa;Max Pool Size=4000;Asynchronous Processing=True;Connect Timeout=5000;Packet Size=2768" SettingsObjectName="TakeoHospitalInventory.My.MySettings" SettingsPropertyName="TakeoDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.INCOME_TYPE" Member="INCOME_TYPEs">
    <Type Name="INCOME_TYPE">
      <Column Name="ICID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ICType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BARCODE" Member="BARCODEs">
    <Type Name="BARCODE">
      <Column Name="BarcodeID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BarcodeNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DONATION" Member="DONATIONs">
    <Type Name="DONATION">
      <Column Name="DonationID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DonationName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RECEIPT_CUSTOMER" Member="RECEIPT_CUSTOMERs">
    <Type Name="RECEIPT_CUSTOMER">
      <Column Name="CustID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CustomerNo" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CusName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Female" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Male" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Sex" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Age" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Occupation" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="OccNo" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Province" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="District" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Commune" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Village" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="IsPatient" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CusNameEng" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ACCOUNT_PAYABLE" Member="ACCOUNT_PAYABLEs">
    <Type Name="ACCOUNT_PAYABLE">
      <Column Name="AccountID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AccountName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ACCOUNT_PAYABLE_DETAIL" Member="ACCOUNT_PAYABLE_DETAILs">
    <Type Name="ACCOUNT_PAYABLE_DETAIL">
      <Column Name="ACC_PAID_ID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ACCOUNTID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="DATE_PAID" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AMOUNT_REAL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AMOUNT_DOLAR" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IS_DOLAR" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IS_RIEL" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DESCRIPTION" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="IS_DELETE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DEPART_ID" Type="System.Decimal" DbType="numeric(18, 0)" CanBeNull="true" />
      <Column Name="DEPART_NAME" Type="System.String" DbType="nvarchar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblPatientReceipt" Member="tblPatientReceipts">
    <Type Name="tblPatientReceipt">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReceiptNo" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IDCashReceipt" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HN" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="PatientName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="CashRiel" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CashUSD" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalRiel" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TotalUSD" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OperationFeeRiel" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OperationFeeUSD" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ArtificialEyeFeeRiel" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ArtificialEyeFeeUSD" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OtherFeeRiel" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="OtherFeeUSD" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ConsultationFeeRiel" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ConsultationFeeUSD" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FollowUpFeeRiel" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FollowUpFeeUSD" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MedicineFeeRiel" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MedicineFeeUSD" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GlassFeeRiel" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GlassFeeUSD" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SocialFeeRiel" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="SocialFeeUSD" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FullFeeRiel" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FullFeeUSD" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Rates" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AmoutWord" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="ConOP" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ConAE" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ConOT" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ConCON" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ConFOL" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ConMED" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ConGLA" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ConSocialFee" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ConFullFee" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ConGeneral" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="CashierIn" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CashierUpdate" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="PrintCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateIn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateNow" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ConPay" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ConDelete" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Years" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Operation" Type="System.String" DbType="VarChar(8000)" CanBeNull="true" />
      <Column Name="IsDonation" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DonationID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="DonationName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DonationPay" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DonateNote" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="HosFee" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CashTotal" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="IsPatientNill" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ReceiptNote" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TIME_CREATE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TIME_ISSUE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ISSUE_BY_DEPART" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RECEIPT" Member="RECEIPTs">
    <Type Name="RECEIPT">
      <Column Name="ReceiptID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReceiptNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReceiptDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CustID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CustomerNo" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MedicReal" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MedicDolar" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="EyeGlassesReal" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="EyeGlassesDolar" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ReadyModDolar" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ReadyModR" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SpectacleDolar" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="SpectacleR" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="FundRaisingDolar" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="FundRaisingR" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="OtherDolar" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="OtherR" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TotalReal" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TotalDolar" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="AmountInWords" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="AmountFigureReal" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="AmountFigureDolar" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ReturnReal" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ReturnDolar" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="IsCurrency" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDonation" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DonationID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PayBySelf" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="PayByDonation" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="IsPaid" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ReceiptNote" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="UserID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IncomType" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Glasses" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonateAmount" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="SupportedAmtDolar" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="SupportedAmtR" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ReceiptType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SubReceiptType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PaidR" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PaidDollar" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="IsOldPatient" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PaymentType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FullAmount" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="NilAmount" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="SocialAmount" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="PaymentCur" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TotalSocial" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="TIME_CREATE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.RECEIPT_DETAIL" Member="RECEIPT_DETAILs">
    <Type Name="RECEIPT_DETAIL">
      <Column Name="ReceiptDID" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReceiptNo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ItemID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ItemPrice" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="ItemQTY" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SubTotalReal" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SubTotalDolar" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="IncomeID" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ReceiptDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ItemCost" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="EXCHANGE_RATE" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
</Database>